/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Empresa;
import model.Marca;
import model.Modelo;
import model.Vehiculo;

/**
 *
 * @author Adamantium
 */
public class VtnAltaDeVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form VtnAltaDeVehiculo
     */
    private Empresa emp = null;
    private Cliente unCliente = null;
    private boolean modificar = false;
    
    public VtnAltaDeVehiculo() {
        initComponents();
    }
    
    public VtnAltaDeVehiculo(Empresa emp) {
        this();
        this.emp = emp;
        cargarMarcas(ComboMarca);
        cargarModelos(ComboModelo);
        camposEstandar();
    }
    
    public VtnAltaDeVehiculo(Empresa emp, Vehiculo unVehiculo) {
        this(emp);       
        this.modificar = true;
        this.unCliente = unVehiculo.getCliente();
        BtnAceptar.setText("Modificar");        
        TxtDni.setText(unVehiculo.getCliente().getDni());
        lblNombre.setText(unVehiculo.getCliente().getApellido() + ", " + unVehiculo.getCliente().getNombre());
        SimpleDateFormat sfd = new SimpleDateFormat("dd-MM-yyyy");
        lblFechaDeNacimiento.setText(sfd.format(unVehiculo.getCliente().getFechaDeNacimiento().getTime())); 
        TxtPatente.setText(unVehiculo.getPatente());
        TxtPatente.disable();
        DateFechaDeCompra.setCalendar(unVehiculo.getFechaDeCompra());
        ComboMarca.setSelectedItem(unVehiculo.getModelo().getMarca());
        ComboModelo.setSelectedItem(unVehiculo.getModelo());
        lblTitulo.setText("Modificar Vehiculo");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        TxtPatente = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboModelo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        ComboMarca = new javax.swing.JComboBox();
        DateFechaDeCompra = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtDni = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblFechaDeNacimiento = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Patente");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        lblTitulo.setText("Alta de Vehiculo");

        jLabel1.setText("Modelo");

        ComboModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Marca");

        ComboMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboMarcaItemStateChanged(evt);
            }
        });

        jLabel7.setText("Fecha de Compra");

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/accept.png"))); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Cliente");

        lblNombre.setText("Nombre");

        lblFechaDeNacimiento.setText("Fecha de Nacimiento");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/magnifier16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnCancelar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(TxtPatente)
                                    .addComponent(DateFechaDeCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(ComboModelo, 0, 133, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblFechaDeNacimiento)
                                    .addComponent(lblNombre)
                                    .addComponent(ComboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(BtnAceptar))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNombre))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaDeNacimiento))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateFechaDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        try {
            String patente;
            patente = TxtPatente.getText();
            if (unCliente == null){
                throw new Exception("Por favor seleccione un cliente");
            }
            if (patente.isEmpty()){
                throw new Exception("Por favor escriba la patente del auto");
            } else {
            }
            if (modificar == false) {
                if (ComboMarca.getSelectedIndex() >= 0 && ComboModelo.getSelectedIndex() >=0) { 
                    Modelo modelo = (Modelo) ComboModelo.getSelectedItem();
                    GregorianCalendar fecha = Modulo.DateChooserToGregorianCalendar(DateFechaDeCompra);
                    this.emp.agregarVehiculo(patente, fecha, modelo, unCliente);
                    JOptionPane.showMessageDialog(null, "Se agrego el vehiculo correctamente.");
                    camposEstandar();
                }else{
                    JOptionPane.showMessageDialog(this, "Seleccione un modelo y marca para el vehiculo.");
                }
            } else if(modificar == true) {
                if (ComboMarca.getSelectedIndex() >= 0 && ComboModelo.getSelectedIndex() >=0) {
                    Modelo modelo = (Modelo) ComboModelo.getSelectedItem();
                    GregorianCalendar fecha = Modulo.DateChooserToGregorianCalendar(DateFechaDeCompra);
                    this.emp.modificarVehiculo(patente, fecha, modelo, unCliente);
                    JOptionPane.showMessageDialog(null, "Se modifico el vehiculo correctamente.");
                    camposEstandar();
                }else{
                    JOptionPane.showMessageDialog(this, "Seleccione un modelo y marca para el vehiculo.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            camposEstandar();
            this.unCliente = this.emp.buscarCliente(TxtDni.getText());
            this.emp.comprobarEstadoActivoCliente(TxtDni.getText());
            lblNombre.setText(unCliente.getApellido() + ", " + unCliente.getNombre());
            SimpleDateFormat sfd = new SimpleDateFormat("dd-MM-yyyy");
            lblFechaDeNacimiento.setText(sfd.format(unCliente.getFechaDeNacimiento().getTime()));   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboMarcaItemStateChanged
        cargarModelos(ComboModelo);
    }//GEN-LAST:event_ComboMarcaItemStateChanged

    //Metodos especificos
    
    private void cargarMarcas(JComboBox unCombo){
        unCombo.removeAllItems();
        Map lista = this.emp.getMarcas();
        Iterator <Marca> it = lista.values().iterator();
        while(it.hasNext()){
            unCombo.addItem(it.next());
        }
    }
    
    private void cargarModelos(JComboBox unCombo){
        unCombo.removeAllItems();
            if(ComboMarca.getSelectedIndex() >= 0){
                List lista = ((Marca)ComboMarca.getSelectedItem()).getModelos();
                Iterator <Modelo> it = lista.iterator();
                while(it.hasNext()){
                unCombo.addItem(it.next());
            }
        }
    }
    
    private void camposEstandar(){
        lblNombre.setText("Nombre");
        lblFechaDeNacimiento.setText("Fecha de Nacimiento");
        Calendar fechaActual = new GregorianCalendar();
        DateFechaDeCompra.setCalendar(fechaActual);
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAltaDeVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAltaDeVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAltaDeVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAltaDeVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAltaDeVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JComboBox ComboMarca;
    private javax.swing.JComboBox ComboModelo;
    private com.toedter.calendar.JDateChooser DateFechaDeCompra;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtPatente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFechaDeNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
