/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Empresa;

/**
 *
 * @author Adamantium
 */
public class VtnPrincipal extends javax.swing.JFrame {

    private Empresa emp;
    
    /**
     * Creates new form VtnPrincipal
     */
    public VtnPrincipal() {
        initComponents();
    }
    
    public VtnPrincipal(Empresa empresa){        
        this.emp = empresa;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuSolicitud = new javax.swing.JMenu();
        ItemMenuServicio = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuEspecialista = new javax.swing.JMenu();
        MiAltaDeEspecialista = new javax.swing.JMenuItem();
        MenuAgenda = new javax.swing.JMenuItem();
        MenuGestionarEspecialistas = new javax.swing.JMenuItem();
        MenuMarcas = new javax.swing.JMenu();
        MiAltaDeMarca = new javax.swing.JMenuItem();
        MenuModelos = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuVehiculos = new javax.swing.JMenu();
        MiAltaDeVehiculo = new javax.swing.JMenuItem();
        MenuGestionarVehiculos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema tu Carrito");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMenu2.setText("Inicio");

        jMenuItem2.setText("Cerrar Sesion");
        jMenu2.add(jMenuItem2);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        MenuSolicitud.setText("Solicitud");
        MenuSolicitud.setName("Solicitud"); // NOI18N

        ItemMenuServicio.setText("Servicio");
        ItemMenuServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuServicioActionPerformed(evt);
            }
        });
        MenuSolicitud.add(ItemMenuServicio);

        jMenuBar1.add(MenuSolicitud);

        MenuClientes.setText("Clientes");

        jMenuItem5.setText("Alta Cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuClientes.add(jMenuItem5);

        jMenuItem3.setText("Gestionar Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuClientes.add(jMenuItem3);

        jMenuBar1.add(MenuClientes);

        MenuEspecialista.setText("Especialistas");

        MiAltaDeEspecialista.setText("Alta de Especialista");
        MiAltaDeEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiAltaDeEspecialistaActionPerformed(evt);
            }
        });
        MenuEspecialista.add(MiAltaDeEspecialista);

        MenuAgenda.setText("Generar Agenda");
        MenuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgendaActionPerformed(evt);
            }
        });
        MenuEspecialista.add(MenuAgenda);

        MenuGestionarEspecialistas.setText("Gestionar Especialistas");
        MenuGestionarEspecialistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestionarEspecialistasActionPerformed(evt);
            }
        });
        MenuEspecialista.add(MenuGestionarEspecialistas);

        jMenuBar1.add(MenuEspecialista);

        MenuMarcas.setText("Marcas");

        MiAltaDeMarca.setText("Alta de Marca");
        MiAltaDeMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiAltaDeMarcaActionPerformed(evt);
            }
        });
        MenuMarcas.add(MiAltaDeMarca);

        jMenuBar1.add(MenuMarcas);

        MenuModelos.setText("Modelos");

        jMenuItem4.setText("Alta de Modelo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuModelos.add(jMenuItem4);

        jMenuBar1.add(MenuModelos);

        MenuVehiculos.setText("Vehiculos");

        MiAltaDeVehiculo.setText("Alta de Vehiculo");
        MiAltaDeVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiAltaDeVehiculoActionPerformed(evt);
            }
        });
        MenuVehiculos.add(MiAltaDeVehiculo);

        MenuGestionarVehiculos.setText("Gestionar Vehiculos");
        MenuGestionarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestionarVehiculosActionPerformed(evt);
            }
        });
        MenuVehiculos.add(MenuGestionarVehiculos);

        jMenuBar1.add(MenuVehiculos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemMenuServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuServicioActionPerformed
        // TODO add your handling code here:
        VtnSolicitudServicio ventana = new VtnSolicitudServicio(this.emp);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_ItemMenuServicioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        VtnAltaDeCliente AltaCliente = new VtnAltaDeCliente(this.emp);
        AltaCliente.setLocationRelativeTo(null);
        AltaCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MiAltaDeEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiAltaDeEspecialistaActionPerformed
        VtnAltaDeEspecialista AltaEspecialista = new VtnAltaDeEspecialista(this.emp);
        AltaEspecialista.setLocationRelativeTo(null);
        AltaEspecialista.setVisible(true);
    }//GEN-LAST:event_MiAltaDeEspecialistaActionPerformed

    private void MiAltaDeMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiAltaDeMarcaActionPerformed
        VtnAltaDeMarca AltaMarca = new VtnAltaDeMarca(this.emp);
        AltaMarca.setLocationRelativeTo(null);
        AltaMarca.setVisible(true);
    }//GEN-LAST:event_MiAltaDeMarcaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VtnGestionClientes GestionCliente = new VtnGestionClientes(this.emp);
        GestionCliente.setLocationRelativeTo(null);
        GestionCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        VtnAltadeModelo ventana = new VtnAltadeModelo(this.emp);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MiAltaDeVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiAltaDeVehiculoActionPerformed
        VtnAltaDeVehiculo ventana = new VtnAltaDeVehiculo(this.emp);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_MiAltaDeVehiculoActionPerformed

    private void MenuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgendaActionPerformed
        VtnGenerarAgenda ventana = new VtnGenerarAgenda(this.emp);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_MenuAgendaActionPerformed

    private void MenuGestionarEspecialistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestionarEspecialistasActionPerformed
        VtnGestionarEspecialistas ventana = new VtnGestionarEspecialistas(this.emp);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_MenuGestionarEspecialistasActionPerformed

    private void MenuGestionarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestionarVehiculosActionPerformed
        VtnGestionarVehiculos ventana = new VtnGestionarVehiculos(this.emp);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_MenuGestionarVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenuServicio;
    private javax.swing.JMenuItem MenuAgenda;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuEspecialista;
    private javax.swing.JMenuItem MenuGestionarEspecialistas;
    private javax.swing.JMenuItem MenuGestionarVehiculos;
    private javax.swing.JMenu MenuMarcas;
    private javax.swing.JMenu MenuModelos;
    private javax.swing.JMenu MenuSolicitud;
    private javax.swing.JMenu MenuVehiculos;
    private javax.swing.JMenuItem MiAltaDeEspecialista;
    private javax.swing.JMenuItem MiAltaDeMarca;
    private javax.swing.JMenuItem MiAltaDeVehiculo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
