/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Empresa;
import model.Especialista;
import model.Funciones;
//import modelo.Funciones;
import model.Vehiculo;

/**
 *
 * @author Adamantium
 */
public class VtnSolicitudServicio extends javax.swing.JFrame implements Observer {

    private Empresa emp;
    private GregorianCalendar diaSeleccionado;
    DefaultListModel modeloEspecialista = new DefaultListModel();
    DefaultListModel modeloHorario = new DefaultListModel();

    /**
     * Creates new form VtnSolicitudServicio
     */
    VtnSolicitudServicio() {
        initComponents();
    }

    /**
     * 
     * @param emp 
     */
    VtnSolicitudServicio(Empresa emp) {
        this();
        this.emp = emp;
        this.emp.addObserver(this);
        this.diaSeleccionado = new GregorianCalendar();
        ListaEspecialistas.setModel(modeloEspecialista);
        ListaHorario.setModel(modeloHorario);
        try {
            CalFecha.getDayChooser().addPropertyChangeListener(
                    new java.beans.PropertyChangeListener() {
                        @Override
                        public void propertyChange(java.beans.PropertyChangeEvent evt) {
                            //evt.getPropertyName().
                            if (evt.getPropertyName().compareTo("day") == 0) {
                                //SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/yyyy");
                                diaSeleccionado = (GregorianCalendar) CalFecha.getCalendar();
                                llenarEspecialistas(diaSeleccionado);
                            }
                        }
                    });
            llenarEspecialistas(diaSeleccionado);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtApellidoYNombre = new javax.swing.JTextField();
        BtnBuscarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ComboVehiculos = new javax.swing.JComboBox();
        CalFecha = new com.toedter.calendar.JCalendar();
        BtnBuscarEspecialista = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEspecialistas = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaHorario = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("Cliente");

        jLabel1.setText("Cliente DNI");

        TxtDni.setText("123123");

        jLabel2.setText("Apellido y Nombre");

        TxtApellidoYNombre.setEditable(false);

        BtnBuscarCliente.setText("Buscar");
        BtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(TxtDni)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TxtApellidoYNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtApellidoYNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnBuscarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehiculos"));
        jPanel2.setToolTipText("Vehiculos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboVehiculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ComboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CalFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CalFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalFechaMouseClicked(evt);
            }
        });

        BtnBuscarEspecialista.setText("Agregar Reserva");
        BtnBuscarEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEspecialistaActionPerformed(evt);
            }
        });

        ListaEspecialistas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaEspecialistasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListaEspecialistas);

        jScrollPane3.setViewportView(ListaHorario);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Especialistas");

        jLabel4.setText("Horarios Libres");

        jLabel5.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnBuscarEspecialista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtnBuscarEspecialista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** rdyr boton boton busca al cliente.
     * 
     * @param evt 
     */
    private void BtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClienteActionPerformed
        // TODO add your handling code here:               
        TxtApellidoYNombre.setText("");
        if (ComboVehiculos.getItemCount() > 0) {
            ComboVehiculos.removeAllItems();
        }
        //se pregunta si el campo no esta vacio.
        if (!TxtDni.getText().isEmpty()) {
            try {
                this.emp.getClientes();
                Cliente aux;
                String dniAux = TxtDni.getText();
                //busca el cliente.
                aux = this.emp.buscarCliente(dniAux);
                //List vehiculos = aux.getVehiculos();
                List vehiculos = this.emp.buscarVehiculosPorCliente(aux);
                //pregunta si tiene algun vehiculo
                if (vehiculos.size() > 0) {
                    Iterator<Vehiculo> it = vehiculos.iterator();
                    TxtApellidoYNombre.setText(aux.getApellido() + ", " + aux.getNombre());
                    while (it.hasNext()) {
                        Vehiculo temp = it.next();
                        ComboVehiculos.addItem(temp);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El cliente no tiene vehiculos asociados.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingrese al menos un digitos.");
        }
    }//GEN-LAST:event_BtnBuscarClienteActionPerformed

    private void llenarHorarios(GregorianCalendar dia, Especialista unEspeci) {
        try {
            if (unEspeci != null) {
                if(dia.after(Funciones.horaCero(new GregorianCalendar()))){
                    Iterator it = unEspeci.horarioDisponible(dia).iterator();
                    modeloHorario.removeAllElements();
                    while(it.hasNext()){
                        modeloHorario.addElement(it.next());
                    }
                }else{
                    modeloHorario.removeAllElements();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "El especialista debe ser correcto.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private void llenarEspecialistas(GregorianCalendar dia) {
        try {
            camposListasEstandar();
            if (ComboVehiculos.getItemCount() > 0) {
                if (dia.after(Funciones.horaCero(new GregorianCalendar()))) {
                    Vehiculo aux = (Vehiculo) ComboVehiculos.getSelectedItem();
                    Map especialistasAux = this.emp.buscarEspecialistasPorMarca(aux.getModelo().getMarca());
                    Iterator<Especialista> it = especialistasAux.values().iterator();
                    while(it.hasNext()){
                        Especialista temp = it.next();
                        try{
                            temp.horarioDisponible(dia);
                            modeloEspecialista.addElement(temp);
                        }catch(Exception ex){
                            //Como el metodo horarioDisponible devuelve una excepcion se agrega un catch para evitar que la excepcion 
                            //sea lanzada y corte el metodo.
                        }
                    }
                } else {
                    modeloEspecialista.removeAllElements();
                }
            }else{
                modeloEspecialista.removeAllElements();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /** Vuelve los campos de tipo lista a sus posiciones o valores iniciales.
     * 
     */
    private void camposListasEstandar(){
        modeloEspecialista.removeAllElements();
        modeloHorario.removeAllElements();
    }
    
    private void BtnBuscarEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarEspecialistaActionPerformed
        try { 
            Cliente auxCliente = null;
            Vehiculo auxVehiculo = null;
            Especialista auxEspecialista = null;
            if (!TxtDni.getText().isEmpty()) {
                String dniAux = TxtDni.getText();
                auxCliente = this.emp.buscarCliente(dniAux);
                if (ComboVehiculos.getItemCount() > 0) {
                    auxVehiculo = (Vehiculo) ComboVehiculos.getSelectedItem();
                    if (!ListaEspecialistas.isSelectionEmpty()) {
                        auxEspecialista = (Especialista) ListaEspecialistas.getSelectedValue();
                        if (!ListaHorario.isSelectionEmpty()) {
                            diaSeleccionado = (GregorianCalendar) Modulo.horaCero(diaSeleccionado);
                            String[] horas = ListaHorario.getSelectedValue().toString().split(":");
                            diaSeleccionado.set(Calendar.HOUR_OF_DAY, Integer.parseInt(horas[0]));
                            diaSeleccionado.set(Calendar.MINUTE, Integer.parseInt(horas[1]));
                            //JOptionPane.showMessageDialog(rootPane, diaSeleccionado.get(Calendar.HOUR_OF_DAY));
                            this.emp.confirmarReserva(auxCliente, auxVehiculo, auxEspecialista, diaSeleccionado);
                            JOptionPane.showMessageDialog(rootPane, "Su reserva a sido exitosa.");  
                            //se utiliza una funcion local para volver todos los campos a sus valores estandares.
                            camposListasEstandar();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un Horario.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un Especialista.");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un Vehiculo.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un cliente.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    }//GEN-LAST:event_BtnBuscarEspecialistaActionPerformed

    private void CalFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalFechaMouseClicked
        diaSeleccionado = (GregorianCalendar) CalFecha.getCalendar();
        llenarEspecialistas(diaSeleccionado);
    }//GEN-LAST:event_CalFechaMouseClicked

    private void ListaEspecialistasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaEspecialistasValueChanged
        if (!ListaEspecialistas.isSelectionEmpty()) {
            llenarHorarios(diaSeleccionado, (Especialista) ListaEspecialistas.getSelectedValue());
        } else {
            //JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un especialista.");
        }
    }//GEN-LAST:event_ListaEspecialistasValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnSolicitudServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnSolicitudServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnSolicitudServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnSolicitudServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnSolicitudServicio().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCliente;
    private javax.swing.JButton BtnBuscarEspecialista;
    private com.toedter.calendar.JCalendar CalFecha;
    private javax.swing.JComboBox ComboVehiculos;
    private javax.swing.JList ListaEspecialistas;
    private javax.swing.JList ListaHorario;
    private javax.swing.JTextField TxtApellidoYNombre;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    public void update(Observable o, Object o1) {
        /*
         llenarHorarios(diaSeleccionado,  (Especialista)ListaEspecialistas.getSelectedValue());
         llenarEspecialistas();
         */
        modeloEspecialista.removeAllElements();
        modeloHorario.removeAllElements();
    }
}
